--- 
- 
  apt: 
    name: "{{ packages }}"
  name: "Install Required SikuliX Dependencies -- Takes about 5 Mins"
  vars: 
    packages: 
      - "autoconf"
      - "automake"
      - "libtool"
      - "autoconf-archive"
      - "libcanberra-gtk0"
      - "libcanberra-gtk-module"
      - "libopencv3.2-java"
      - "pkg-config"
      - "libcairo2-dev"
      - "libpango1.0-dev"
      - "libicu-dev"
      - "zlib1g-dev"
      - "libtiff5-dev"
      - "libjpeg8-dev"
      - "xrdp"
      - "python-unittest2"
- 
  get_url: 
    dest: "/tmp/{{ leptonica_version }}.tar.gz"
    url: "{{ leptonica_tarball_url }}"
  name: "Downloading Leptonica sources"
  register: leptonica_source
  retries: 5
  delay: 5
  until: leptonica_source is success
- 
  name: "Unpacking Leptonica"
  register: leptonica_source_unpack
  unarchive: 
    copy: false
    dest: /tmp/
    src: "{{ leptonica_source.dest }}"
  when: leptonica_source.changed
- 
  args: 
    chdir: "{{ leptonica_install_dir }}"
  command: "./configure"
  name: "Configuring leptonica source"
  register: leptonica_configure
  when: "leptonica_source_unpack is changed"
- 
  args: 
    chdir: "{{ leptonica_install_dir }}"
  become: true
  name: "Installing Leptonica -- Takes about 7 Mins"
  shell: "make && make install"
  when: "leptonica_configure is changed"
- 
  get_url: 
    dest: "/tmp/{{ tesseract_version }}.tar.gz"
    url: "{{ tesseract_tarball_url }}"
  name: "Downloading tesseract sources"
  register: tesseract_source
  retries: 5
  delay: 5
  until: tesseract_source is success
- 
  name: "Unpacking tesseract"
  register: tesseract_source_unpack
  unarchive: 
    copy: false
    dest: /tmp/
    src: "{{ tesseract_source.dest }}"
  when: tesseract_source.changed
- 
  args: 
    chdir: "{{ tesseract_install_dir }}"
  name: "Configuring tesseract source"
  register: tesseract_configure
  shell: " ./autogen.sh && ./configure --enable-debug"
  when: "tesseract_source_unpack is changed"
- 
  args: 
    chdir: "{{ tesseract_install_dir }}"
  become: true
  name: "Installing tesseract -- Takes about 10 Mins"
  shell: 'LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make && make install && make install-langs && ldconfig'
  when: "tesseract_configure is changed"
- 
  copy: 
    dest: /home/vagrant/Desktop/
    src: /vagrant/Sikulix/deps/Sikuli.desktop
  name: "Adding Desktop Icon for Sikulix"
- 
  name: Set Sikulix to start on User Login
  file: >
    src=/vagrant/Sikulix/deps/Sikulix.sh
    dest=/etc/profile.d/Sikulix.sh
    state=link
- 
  name: Set Add OpenCV to Bin
  file: >
    src=/usr/lib/jni/libopencv_java320.so
    dest=/usr/lib/libopencv_java.so
    state=link
- 
  name: "Changing perm of Desktop Icon"
  file:
    path:  /home/vagrant/Desktop/Sikuli.desktop
    owner: vagrant
    mode: "a+x"
- 
  name: "Changing perm of User Desktop"
  file:
    path:  /home/vagrant/Desktop
    owner: vagrant
    mode: "0777"
- 
  get_url: 
    dest: "/vagrant/Sikulix/deps/jruby-complete-9.2.7.0.jar"
    url: "https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.2.7.0/jruby-complete-9.2.7.0.jar"
  name: "Downloading jruby sources"
  register: jruby_source
  retries: 5
  delay: 5
  until: jruby_source is success
- 
  get_url: 
    dest: "/vagrant/Sikulix/deps/jython-standalone-2.7.1.jar"
    url: "https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.1/jython-standalone-2.7.1.jar"
  name: "Downloading jython sources"
  register: jython_source
  retries: 5
  delay: 5
  until: jython_source is success
- 
  get_url: 
    dest: "/vagrant/sikulixapi.jar"
    url: "https://raiman.github.io/SikuliX1/sikulixapi.jar"
  name: "Downloading SikulixJarAPI sources"
  register: SikulixJarAPI_source
  retries: 5
  delay: 5
  until: SikulixJarAPI_source is success
- 
  get_url: 
    dest: "/vagrant/sikulix.jar"
    url: "https://raiman.github.io/SikuliX1/sikulix.jar"
  name: "Downloading SikulixJar sources"
  register: SikulixJar_source
  retries: 5
  delay: 5
  until: SikulixJar_source is success
