--- 
hosts: 
  - 
    autostart: true
    box: ubuntu/bionic64
    folders: 
      - 
        map: ./conf
        to: /vagrant
    gateway: 192.168.2.1
    identifier: domino4wine.mydomain.net
    ip: 192.168.2.181
    mac: 525400c9c010
    name: domino4wine
    netmask: 255.255.0.0
    branch: "Domino-Notes"
    provider: 
      - 
        directive: memory
        value: "4096"
      - 
        directive: cpus
        value: "4"
    provision: 
      - ./scripts/aliases.sh
path: .
