##################################################################################
##################################################################################
##    Copyright (C) 2019-present Prominic.NET, Inc.                             ##
##                                                                              ##
##    This program is free software: you can redistribute it and/or modify      ##
##    it under the terms of the Server Side Public License, version 1,          ##
##    as published by MongoDB, Inc.                                             ##
##                                                                              ##
##    This program is distributed in the hope that it will be useful,           ##
##    but WITHOUT ANY WARRANTY; without even the implied warranty of            ##
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             ##
##    Server Side Public License for more details.                              ##
##                                                                              ##
##    You should have received a copy of the Server Side Public License         ##
##    along with this program. If not, see:                                     ##
##                                                                              ##
##    http://www.mongodb.com/licensing/server-side-public-license               ##
##                                                                              ##
##    As a special exception, the copyright holders give permission to link the ##
##    code of portions of this program with the OpenSSL library under certain   ##
##    conditions as described in each individual source file and distribute     ##
##    linked combinations including the program with the OpenSSL library. You   ##
##    must comply with the Server Side Public License in all respects for       ##
##    all of the code used other than as permitted herein. If you modify file(s)##
##    with this exception, you may extend this exception to your version of the ##
##    file(s), but you are not obligated to do so. If you do not wish to do so, ##
##    delete this exception statement from your version. If you delete this     ##
##    exception statement from all source files in the program, then also delete##
##    it in the license file.                                                   ##
##################################################################################
##################################################################################
--- 
- 
  name: Adding Python3 PSUtil
  apt:
    name: python3-psutil
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/session/idle-delay
    value: "uint32 0"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/screensaver/lock-enabled
    value: "false"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/screensaver/idle-activation-enabled
    value: "false"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/screensaver/ubuntu-lock-on-suspend
    value: "false"
  name: "Disable Lock on suspend"
- 
  alternatives: 
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  name: "correct java version selected"
- 
  become_user: vagrant
  name: "Set Display to 1440x900"
  shell: "Xvfb -ac :0 -screen 0 1440x900x24+32 & sleep 3 && export DISPLAY=:0"
- 
  become_user: vagrant
  name: "Set Display to 1440x900"
  shell: "export XAUTHORITY=/home/vagrant/.Xauthority"
- 
  copy: 
    dest: /home/vagrant/Desktop/
    src: /vagrant/Sikulix/deps/Sikuli.desktop
  name: "Adding Desktop Icon for Sikulix"
- 
  copy: 
    dest: /home/vagrant/.config/autostart
    src: /vagrant/jenkins/jenkins.desktop
  name: "Adding Jenkins to Autostart"
- 
  name: "Changing perm of Desktop Icon"
  file:
    path:  /home/vagrant/Desktop/Sikuli.desktop
    owner: vagrant
    mode: "a+x"
- 
  become: true
  name: "Changing Desktop Permissions"
  file:
    path:  /home/vagrant/Desktop/
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'
- 
  name: Update all packages to the latest version
  apt:
    upgrade: dist
- 
  name: Downloading Base Bottle
  get_url: 
    url: https://www.m4kr.net/base.deb
    dest: /home/vagrant/base.deb
- 
  name: Installing Base Bottle
  command: sudo dpkg -i /home/vagrant/base.deb
