##################################################################################
##################################################################################
##    Copyright (C) 2019-present Prominic.NET, Inc.                             ##
##                                                                              ##
##    This program is free software: you can redistribute it and/or modify      ##
##    it under the terms of the Server Side Public License, version 1,          ##
##    as published by MongoDB, Inc.                                             ##
##                                                                              ##
##    This program is distributed in the hope that it will be useful,           ##
##    but WITHOUT ANY WARRANTY; without even the implied warranty of            ##
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             ##
##    Server Side Public License for more details.                              ##
##                                                                              ##
##    You should have received a copy of the Server Side Public License         ##
##    along with this program. If not, see:                                     ##
##                                                                              ##
##    http://www.mongodb.com/licensing/server-side-public-license               ##
##                                                                              ##
##    As a special exception, the copyright holders give permission to link the ##
##    code of portions of this program with the OpenSSL library under certain   ##
##    conditions as described in each individual source file and distribute     ##
##    linked combinations including the program with the OpenSSL library. You   ##
##    must comply with the Server Side Public License in all respects for       ##
##    all of the code used other than as permitted herein. If you modify file(s)##
##    with this exception, you may extend this exception to your version of the ##
##    file(s), but you are not obligated to do so. If you do not wish to do so, ##
##    delete this exception statement from your version. If you delete this     ##
##    exception statement from all source files in the program, then also delete##
##    it in the license file.                                                   ##
##################################################################################
##################################################################################
--- 
- 
  name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3-psutil
    - xvfb
    - preload
    - unix2dos
    - dos2unix
- 
  name: Set timezone to America/Chicago
  timezone:
    name: America/Chicago
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/session/idle-delay
    value: "uint32 0"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/screensaver/lock-enabled
    value: "false"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/screensaver/idle-activation-enabled
    value: "false"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: vagrant
  dconf: 
    key: /org/gnome/desktop/screensaver/ubuntu-lock-on-suspend
    value: "false"
  name: "Disable Lock on suspend"
- 
  alternatives: 
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  name: "correct java version selected"
- 
  become_user: vagrant
  name: "Set Display to 1440x900"
  shell: "export XAUTHORITY=/home/vagrant/.Xauthority"
- 
  copy: 
    dest: /home/vagrant/Desktop/
    src: /vagrant/Sikulix/deps/Sikuli.desktop
  name: "Adding Desktop Icon for Sikulix"
- 
  name: "Changing perm of Desktop Icon"
  file:
    path:  /home/vagrant/Desktop/Sikuli.desktop
    owner: vagrant
    mode: "a+x"
- 
  become: true
  name: "Changing Desktop Permissions"
  file:
    path:  /home/vagrant/Desktop/
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'
- 
  name: Update all packages to the latest version
  apt:
    upgrade: dist
  retries: 3
  delay: 3
- 
  name: Downloading Base Bottle
  get_url: 
    url: https://www.m4kr.net/Notes10Demo.deb
    dest: /home/vagrant/Notes10Demo.deb
    timeout: 300
- 
  name: Installing Base Bottle
  command: sudo dpkg -i /home/vagrant/Notes10Demo.deb
- 
  name: "Starting Jenkins Service"
  service: 
    enabled: true
    name: jenkins
    state: restarted
- 
  become: true
  name: "Adding Vagrant-Share to Desktop  for Ease of Access"
  file:
    path:  /home/vagrant/Desktop/Vagrant-Share
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'
- 
  become: true
  name: "Adding Jenkins-Jobs to Desktop  for Ease of Access"
  file:
    path:  /home/vagrant/Desktop/Jenkins-Jobs
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'
- 
  become: true
  name: "Adding Sikulix Scripts to Desktop for Ease of Access"
  file:
    path:  /home/vagrant/Desktop/Sikulix-Scripts
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'
- 
  become: true
  name: "Adding Sikulix Scripts to Desktop for Ease of Access"
  file:
    path:  /home/vagrant/Desktop/AppInstall
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'
- 
  become: true
  name: "Adding HTML5 to Desktop for Ease of Access"
  file:
    path:  /home/vagrant/Desktop/HTML5
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'
- 
  name: Mounting Vagrant-Share Jobs to Desktop folder
  mount:
    path: /home/vagrant/Desktop/Vagrant-Share
    src: /vagrant
    opts: bind
    state: mounted
    fstype: none
- 
  name: Mounting Sikulix Scripts to Desktop folder
  mount:
    path: /home/vagrant/Desktop/Sikulix-Scripts
    src: /home/vagrant/Desktop/Vagrant-Share/Sikulix/scripts
    opts: bind
    state: mounted
    fstype: none
- 
  name: Mounting Jenkins Jobs to Desktop folder
  mount:
    path: /home/vagrant/Desktop/Jenkins-Jobs
    src: /home/vagrant/Desktop/Vagrant-Share/jenkins/jobs
    opts: bind
    state: mounted
    fstype: none
- 
  name: Mounting AppInstall to Desktop
  mount:
    path: /home/vagrant/Desktop/AppInstall
    src: /home/vagrant/Desktop/Vagrant-Share/AppInstall
    opts: bind
    state: mounted
    fstype: none
-
  name: Copy Desktop Icons to /usr/share/applications
  copy:
    src: /vagrant/Desktop/{{item}}
    dest: /usr/share/applications
    mode: 0774
  with_items:
    ['IBM+Domino+Admin.desktop','IBM+Notes.desktop','Logout.desktop','Admin.ico','Logout.png','logout.sh','Notes.ico']
-
  name: Set Notes to Start for all Users
  copy:
    src: /vagrant/Desktop/IBM+Notes.desktop
    dest: /etc/xdg/autostart/
    mode: 0774
-
  name: Creating userconf DB Directory
  file:
    path: /etc/dconf/db/local.d/
    state: directory
-
  name: Creating userconf DB Directory
  file:
    path: /etc/dconf/db/profile/
    state: directory
-
  name: Setting User Dconf
  copy:
    src: /vagrant/Desktop/{{item}}
    dest: /etc/dconf/profile/{{item}}
    mode: 0774
  with_items:
    ['user']
-
  name: Setting Global Dconf
  copy:
    src: /vagrant/Desktop/{{item}}
    dest: /etc/dconf/db/local.d/userconf
    mode: 0774
  with_items:
    ['userconf']
- name: Updating dconf Configuration for all users
  command: dconf update
-
  name: Cloning Top-icons Gnome Extension
  git:
    repo: https://github.com/phocean/TopIcons-plus.git
    dest: /usr/local/src/TopIcons-plus
    force: yes
-
  name: "Installing Top-icons Gnome Extension Plus for all users"
  make:
    chdir: /usr/local/src/TopIcons-plus
    target: install
    params:
      INSTALL_PATH: /usr/share/gnome-shell/extensions
-
  name: Cloning dash-to-panel Gnome Extension
  git:
    repo: https://github.com/home-sweet-gnome/dash-to-panel.git
    dest: /usr/local/src/dash-to-panel
-
  name: "Installing dash-to-panel Gnome Extension Plus for all users"
  make:
    chdir: /usr/local/src/dash-to-panel
    target: install
    params:
      DESTDIR: /
-
  name: Cloning extend-panel-menu Gnome Extension
  git:
    repo: https://github.com/julio641742/extend-panel-menu.git
    dest: /usr/local/src/extend-panel-menu
-
  make:
    chdir: /usr/local/src/extend-panel-menu
    target: all
    params:
      INSTALLBASE: /usr/share/gnome-shell/extensions
  name: "Installing extend-panel-menu Gnome Extension Plus for all users"
-
  make:
    chdir: /usr/local/src/extend-panel-menu
    target: install
    params:
      INSTALLBASE: /usr/share/gnome-shell/extensions
  name: "Installing extend-panel-menu Gnome Extension Plus for all users"
